networks:
  web:
    external: true
services:
  npm-addict:
    image: mvila/npm-addict:production
    restart: always
    container_name: npm-addict
    hostname: host2
    environment:
      - STORE_URL
      - GITHUB_PERSONAL_ACCESS_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - SLACK_INCOMING_WEBHOOK_URL
      - SLACK_INCOMING_WEBHOOK_CHANNEL
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
    labels:
      - traefik.http.routers.npm-addict-api.rule=Host(`api.npmaddict.com`)
      - traefik.http.routers.npm-addict-api.tls=true
      - traefik.http.routers.npm-addict-api.tls.certresolver=lets-encrypt
      - traefik.http.routers.npm-addict-api.service=npm-addict-api
      - traefik.http.services.npm-addict-api.loadbalancer.server.port=8831
      - traefik.http.routers.npm-addict-website.rule=Host(`npmaddict.com`)
      - traefik.http.routers.npm-addict-website.tls=true
      - traefik.http.routers.npm-addict-website.tls.certresolver=lets-encrypt
      - traefik.http.routers.npm-addict-website.service=npm-addict-website
      - traefik.http.services.npm-addict-website.loadbalancer.server.port=8832
    networks:
      - web
